services:
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_DATABASE: forme
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - '27019:27017'
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: forme
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306'
    # comment
