services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: forme
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forme-network

  app:
    container_name: app-spring
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/forme
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - forme-network

volumes:
  postgres_data:
# Ajout de Network pour les services, pour permettre la communication entre les services
networks:
  forme-network:
