services:
  postgres:
    image: 'postgres:17.0'
    environment:
      POSTGRES_DB: forme
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: